version: "3.8"
services:
  api:
    build: .
    container_name: archer_api
    command: python archer/manage.py runserver 0.0.0.0:8765
    volumes:
      - .:/opt/projects/archer
    ports:
      - "8765:8765"
    depends_on:
       - mysql
  mysql:
    image: mysql:5.7
    container_name: archer_mysql
    volumes:
      - archer_mysql:/var/lib/mysql
    ports:
      - 3406:3306
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: archer
      MYSQL_USER: archer
      MYSQL_PASSWORD: archer
      MYSQL_DATABASE: archer

volumes:
  archer_mysql:
